# Generated by Django 3.2.9 on 2021-11-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproduct',
            unique_together={('stock', 'product')},
        ),
    ]
